workspace(name = "com_github_aisbaa_deb_packages_integration_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

#
# docker rules ---------------------------------------------------------------
#

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "4521794f0fba2e20f3bf15846ab5e01d5332e587e9ce81629c7f96c793bb7036",
    strip_prefix = "rules_docker-0.14.4",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.4/rules_docker-v0.14.4.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "debian10",
    registry = "index.docker.io",
    repository = "debian",
    # digest = "sha256-b838471e0d4a19fd67dd6adb5961315d9b3e8a205e8f3970d7a75cd746001c5b",
    tag = "buster-20200908",
)

#
# deb_packages rules ---------------------------------------------------------
#

http_archive(
    name = "aisbaa_rules_deb_packages",
    sha256 = "RELEASE_ARCHIVE_CHECKSUM",
    urls = [
        # replaces this with url from github in your project
        "file://RELEASE_ARCHIVE_LOCATION",
    ],
)

load("@aisbaa_rules_deb_packages//deb_packages:defs.bzl", "deb_repository")
load("@aisbaa_rules_deb_packages//deb_packages:deps.bzl", "deb_packages_setup")

deb_packages_setup(
    the_tool_path="file://RELEASE_THE_TOOL_LOCATION",
    the_tool_sha="RELEASE_THE_TOOL_CHECKSUM",
)

# dowload gpg key for repo and
http_file(
    name = "buster_archive_key",
    sha256 = "9c854992fc6c423efe8622c3c326a66e73268995ecbe8f685129063206a18043",
    urls = ["https://ftp-master.debian.org/keys/archive-key-10.asc"],
)


deb_repository(
    name = "debian_buster_amd64_pkgs",
    arch = "amd64",
    distro = "buster",
    distro_type = "debian",
    mirrors = [
        "http://deb.debian.org/debian",
    ],
    packages = {
    },
    packages_sha256 = {
    },
    pgp_key = "buster_archive_key",
)
