load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name="update_deb_packages_bzl_tar",
    srcs=[
        "update_deb_packages.bzl",
    ],
    visibility = ["//:__subpackages__"]
)
